### ISSUE TITLE
Works with Debian derivates only

### ISSUE THREAD

**Issue by mudrd8mz** [hwuerz/moodle-local_changeloglib#1]
```
$output = shell_exec('dpkg -s poppler-utils 2>&1');
```
does not work on Linux distributions that are not based on Debian, even if the `pdftotext` is available. I would suggest to follow what Moodle normally does, and let the admin define the path to a binary to be used - similarly to https://docs.moodle.org/34/en/System_paths

It does not look right to limit the usage to a particular family of OS distribution, however common it is. Especially if there is no particular reason for it.

**Comment by hwuerz** [comment]
Hi David,

thanks for having a look on my plugins and approving them. I was very happy about this.

I fixed the above command in commit 8b60c9881f45f8c2c5cf6fae7a03e5a60561cbb4
