### ISSUE TITLE
Why does it manually drop local_changeloglib_backup table?

### ISSUE THREAD

**Issue by mudrd8mz** [hwuerz/moodle-local_changeloglib#2]
The db/uninstall.php file seems to explicitly drop the table local_changeloglib_backup_lib::BACKUP_TABLE (local_changeloglib_backup) which is defined in install.xml. I live in impression that tables defined in install.xml are dropped implicitly. Why do you drop it explicitly here?

**Comment by hwuerz** [comment]
This was an error. Fixed in f82f432cd9693d78a685145de02b63f2a98a9106
